name: Deploy Staging

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    name: deploy-staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore solution
        run: dotnet restore ./src/Synergy.Admin.sln

      - name: Build solution
        run: dotnet build ./src/Synergy.Admin.sln --configuration Release --no-restore

      - name: Publish web project
        run: dotnet publish ./src/Synergy.Admin.Web/Synergy.Admin.Web.csproj --configuration Release --output ./publish --no-build

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: synergy-admin-staging
          path: ./publish

      - name: Simulated deploy
        run: |
          echo "Deploy do ambiente STAGING"
          echo "Aqui você vai colocar Azure, AWS, IIS, VPS ou Docker depois."